### ISSUE TITLE
How to use this gtest for STM32F407G ?

### ISSUE THREAD

**Issue by lenhatquang2512** [CharlesDias/stm32_gtest_c_code#8]
Hi, thank you a lot for your repository.

I am learning STM32 and Google Test, and I want to use gtest to test codes for STM32F407. I read your README file, and I know that I need to use Docker to pull and build the test, but if I want to use it for a different STM32 MCU (not Nucleo), how do I use your repo to do that? Sorry if I asked something wrong here because I am a beginner to embedded systems. Thank you.

**Comment by CharlesDias** [comment]
Hi, @lenhatquang2512. 

If you are a new programmer, I recommend you to start with something more simple than Gtest, like this [Udemy Unit Testing](https://www.udemy.com/course/unit-testing-and-other-embedded-software-catalysts/). This is appropriate to beginner. Gtest is recommended for programmers that use C++. I'm using Gtest for C because I desired to keep using just one unit test tool.

**Comment by CharlesDias** [comment]
However, if you really want to try Gtest with MCU, starting to understand you the STM32CudeIDE works, how to use CMake and how this is repository is structure. This is the path! :)
