### ISSUE TITLE
Using arm-none-eabi 

### ISSUE THREAD

**Issue by Tiket-s8d** [CharlesDias/stm32_gtest_c_code#9]
Can you tell me why you don't use a compiler arm-none-eabi-gcc and arm-none-eabi-g++ ?

**Comment by CharlesDias** [comment]
Hi, @Tiket-s8d.

In this current version, I'm using the STM32CubeIDE for building and compiling the application project. The STM32CubeIDE uses the GCC ARM version. For test code project, I have to use the GCC for x86_x64 version because the GTest runs on an Ubuntu docker container. The original version of GTest is not able to runs on MCU.
